ACM_Registration_Portal/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('MainApp.urls', namespace='MainApp')),
]

MainApp/urls.py
from django.contrib import admin
from django.urls import path
from .views import *

app_name = 'MainApp'

urlpatterns = [
    path('', home, name='home'),
    path('login/', loginPage, name='login'),
    path('event/', event, name='event'),
    path('logout/',logoutPage,name='logout'),
    path('signin/',signin,name='signin'),
    path('register/',register,name='register'),
    path('about/',about,name='about'),
    path('account/',account,name='account'),
    path('account/updatePassword/<int:id>',updatePassword,name='updatePassword'),
    path('recovery/',recovery,name='recovery'),
    path('sendpassword/',sendpassword,name='sendpassword'),
    path('registration/',registration,name='registration'),
    path('createteam/',createteam,name='createteam'),
    path('checkteam/',checkteam,name='checkteam'),
    path('deleteteam/<str:team_name>',deleteteam,name='deleteteam'),
    path('problems/',problems,name='problems'),
    path('getteams/',getteams,name='getteams'),
]

MainApp/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.core.validators import MaxValueValidator, MinValueValidator
from .managers import CustomUserManager


class CustomUser(AbstractUser):
    username = None
    email = models.EmailField(_("email address"), unique=True)
    USN = models.CharField(max_length=10)
    USERNAME_FIELD = "email"
    is_registered=models.BooleanField(default=False)
    year=models.CharField(max_length=4,default='2025')
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    def __str__(self):
        return self.email


class Team(models.Model):
    team_name=models.CharField(max_length=100,primary_key=True)
    team_leader=models.ForeignKey(CustomUser,on_delete=models.CASCADE)
    team_member1=models.ForeignKey(CustomUser,on_delete=models.CASCADE,related_name='team_member1',null=True,blank=True)
    team_member2=models.ForeignKey(CustomUser,on_delete=models.CASCADE,related_name='team_member2',null=True,blank=True)
    team_member3=models.ForeignKey(CustomUser,on_delete=models.CASCADE,related_name='team_member3',null=True,blank=True)
    problem_no=models.IntegerField(default=1,validators=[MaxValueValidator(25), MinValueValidator(1)])
    def __str__(self):
        return self.team_name

MainApp/views.py
from django.http import JsonResponse
from django.shortcuts import render, HttpResponse, HttpResponseRedirect
from django.contrib.auth import authenticate, login,logout
from .models import *
import random
from django.core.mail import send_mail
from ACM_Registration_Portal.settings import EMAIL_HOST_USER
import random
import string
from django.conf import settings
import os
import csv

def generate_random_password(length):
    characters = string.ascii_letters + string.digits
    return ''.join(random.choice(characters) for _ in range(length))

# Create your views here.
def home(request):
    # send_mail(
    #     'Subject here',
    #     'Here is the message.',
    #     EMAIL_HOST_USER,
    #     ['shubhammirashi303@gmail.com'],
    #     fail_silently=False,
    # )
    return render(request,'MainApp/home.html')

def loginPage(request):
    return render(request,'MainApp/login.html')

def event(request):
    return render(request,'MainApp/event.html')

def logoutPage(request):
    logout(request)
    return home(request)

def signin(request):
    if request.method == 'POST':
        email = request.POST['email']
        password = request.POST['password']
        print(email,password)
        user = authenticate(request, email=email, password=password)
        if user is not None:
            login(request,user)
            print("success")
            return JsonResponse({'data':'success'})
        else:
            return HttpResponse(status=401)
    return HttpResponse(status=404)

def register(request):
    if request.method == 'POST':
        email = request.POST['email']
        USN=request.POST['USN']
        name=request.POST['name']
        year=request.POST['year']
        print(email,USN,name,year)
        password = generate_random_password(6)
        if CustomUser.objects.filter(email=email).exists():
            val=CustomUser.objects.get(email=email)
            val.set_password(password)
        else:
            print("he must login")
            val=CustomUser(email=email,USN=USN,first_name=name,year=year)
            val.set_password(password)
        send_mail(
            'Credentials for ACM Nexus',
            "Your username is "+email+"\n"+'Your password is '+password,
            EMAIL_HOST_USER,
            [email],
            fail_silently=False,
        )
        val.save()
        return render(request,'MainApp/confirmation.html')
    return HttpResponse(status=404)

def about(request):
    return render(request,'MainApp/about.html')

def account(request):
    return render(request,'MainApp/account.html')

def updatePassword(request,id):
    if request.method=='POST':
        user = CustomUser.objects.get(id=id)
        # print(user)
        # print(request.POST['password'])
        user.set_password(request.POST.get('password'))
        user.save()
        return HttpResponseRedirect('/account')
    return HttpResponse(status=404)

def recovery(request):
    return render(request,'MainApp/recovery.html')

def sendpassword(request):
    if request.method=='POST':
        email=request.POST['email']
        if CustomUser.objects.filter(email=email).exists():
            user=CustomUser.objects.get(email=email)
            password=generate_random_password(6)
            user.set_password(password)
            send_mail(
                'Credentials for ACM Nexus',
                "Your username is "+email+"\n"+'Your password is '+password,
                EMAIL_HOST_USER,
                [email],
                fail_silently=False,
            )
            user.save()
            return render(request,'MainApp/confirmation.html')
        return render(request,'MainApp/confirmation.html')
    return HttpResponse(status=404)

def registration(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect('/login')
    elif Team.objects.filter(team_leader=request.user).exists():
        return render(request,'MainApp/registered.html',context={'team':Team.objects.get(team_leader=request.user)})
    elif Team.objects.filter(team_member1=request.user).exists():
        return render(request,'MainApp/registered.html',context={'team':Team.objects.get(team_member1=request.user)})
    elif Team.objects.filter(team_member2=request.user).exists():
        return render(request,'MainApp/registered.html',context={'team':Team.objects.get(team_member2=request.user)})
    elif Team.objects.filter(team_member3=request.user).exists():
        return render(request,'MainApp/registered.html',context={'team':Team.objects.get(team_member3=request.user)})
    return render(request,'MainApp/registration.html')

def createteam(request):
    if request.method=='POST':
        team_name=request.POST['name']
        if Team.objects.filter(team_name=team_name).exists():
            return HttpResponse(status=404)
        else:
            return render(request,'MainApp/registration.html')
    return HttpResponse(status=404)

def checkteam(request):
    if request.method=='POST':
        team_name=request.POST['name']
        team_leader=request.POST['email1']
        team_member1 = request.POST['email2']
        team_member2 = request.POST['email3']
        team_member3 = request.POST['email4']
        problem_number=request.POST.get('problem')
        print(team_name,team_member1,team_member2,team_member3)
        print(CustomUser.objects.filter(email=team_member1))
        if Team.objects.filter(team_name=team_name).exists():
            return HttpResponse(status=404,reason='Team Name already exists\n Try with different name')
        elif problem_number not in [str(i) for i in range(1,26)]:
            return HttpResponse(status=404,reason='Problem Number is not valid')
        elif not CustomUser.objects.filter(email=team_member1).exists():
            return HttpResponse(status=404,reason='Team Member 2 doesn\'t exists')
        elif not CustomUser.objects.filter(email=team_member2).exists():
            return HttpResponse(status=404,reason='Team Member 3 doesn\'t exists')
        elif not CustomUser.objects.filter(email=team_member3).exists():
            return HttpResponse(status=404,reason='Team Member 4 doesn\'t exists')
        elif Team.objects.filter(team_member1=CustomUser.objects.get(email=team_member1)).exists():
            return HttpResponse(status=404,reason='Team Member 2 already has team')
        elif Team.objects.filter(team_member2=CustomUser.objects.get(email=team_member2)).exists():
            return HttpResponse(status=404,reason='Team Member 3 already has team')
        elif Team.objects.filter(team_member3=CustomUser.objects.get(email=team_member3)).exists():
            return HttpResponse(status=404,reason='Team Member 4 already has team')
        else:
            u1 = CustomUser.objects.get(email=team_leader)
            u1.is_registered = True
            u2 = CustomUser.objects.get(email=team_member1)
            u2.is_registered = True
            u3 = CustomUser.objects.get(email=team_member2)
            u3.is_registered = True
            u4 = CustomUser.objects.get(email=team_member3)
            u4.is_registered = True
            val = Team(team_name=team_name, team_leader=u1, team_member1=u2, team_member2=u3, team_member3=u4,
                       problem_no=problem_number)
            val.save()
            u1.save()
            u2.save()
            u3.save()
            u4.save()
            return JsonResponse({'data':'success'})
    return HttpResponse(status=404)

def deleteteam(request,team_name):
    if request.method=='POST':
        team=Team.objects.get(team_name=team_name)
        u1 = team.team_leader
        u2 = team.team_member1
        u3 = team.team_member2
        u4 = team.team_member3
        u1.is_registered=False
        u2.is_registered=False
        u3.is_registered=False
        u4.is_registered=False
        u1.save()
        u2.save()
        u3.save()
        u4.save()
        team.delete()
        return HttpResponseRedirect('/account')
    return HttpResponse(status=404)


def problems(request):
    f = open(os.path.join(settings.STATIC_ROOT, 'data/data.csv'), 'r')
    reader = csv.reader(f)
    next(reader)
    data_list = list(reader)

    s = {}
    theme = {}
    no = 1
    count = 1
    val = "Sustainability and Environment"

    for a in data_list:
        if val == a[1]:
            if count not in s:
                s[count] = []
            s[count].append((no, a[0]))
            no += 1
        else:
            theme[count] = val
            count += 1
            val = a[1]

            if count not in s:
                s[count] = []
            s[count].append((no, a[0]))
            no += 1

    theme[count] = val

    f.close()
    return render(request, 'MainApp/problems.html', context={'theme': theme.items(), 'data': s.items()})

def getteams(request):
    if request.user.is_superuser:
        f=open(os.path.join(settings.STATIC_ROOT,'data/teams.csv'),'w',newline='')
        writer=csv.writer(f)
        writer.writerow(['Team Name','Team Leader','Team Member 1','Team Member 2','Team Member 3','Problem Number'])
        for team in Team.objects.all():
            writer.writerow([team.team_name,team.team_leader.email,team.team_member1.email,team.team_member2.email,team.team_member3.email,team.problem_no])
        f.close()
        return JsonResponse({'data':list(Team.objects.all().values())})
    return HttpResponse(status=404)

MainApp/templates/MainApp/about.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
    <title>About</title>
    <link rel="stylesheet" href="{% static 'MainApp/about.css'%}">
    
{% endblock head %}

{% block body %}
    <div class="inner-container">
        <div class="about-header">
            <img src="{% static 'Images/logo.png' %}" class="animate__animated  animate__jello" height="100px" />
            <span class="title-about animate__animated animate__bounceInDown">ACM GIT</span>
        </div>
        <main class="main">
            <section class="section">
              <h2 class="heading">Our Mission</h2>
              <p>At ACM KLS GIT, our mission is to provide a platform for students interested in computer science and related fields</p>
            </section>
        
            <section class="section">
              <h2 class="heading">Get Involved</h2>
              <p>Join us in exploring the vast realms of computing and shaping the future through technology.</p><br>
              <p>Connect with us:</p>
              <a href="https://www.instagram.com/acm_klsgit?utm_source=ig_web_button_share_sheet&igsh=OGQ5ZDc2ODk2ZA==">
                <div class="fa fa-instagram insta "></div>
              </a>
            </section>
          </main>

</div>


{% endblock body %}

MainApp/templates/MainApp/account.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
    <link rel="stylesheet" href="{% static 'MainApp/account.css' %}">
{% endblock head %}
{% block body %}
<form action="updatePassword/{{user.id}}" method="post" class="block" id="block" onsubmit="return validateForm()">
    <div class="inner-block">
        {% csrf_token %}
        <h1>Change Password</h1>
        <input type="text" id="password" name="password" class="pass" placeholder="Password" required>
        <input type="password" id="password2"  class="pass" placeholder="Re-Enter Password" required>
        <div class="button">
            <div class="cancel" onclick="closeBlock()">Cancel</div>
            <input class="submit" type="submit" value="Submit">
        </div>
    </div>
</form>
    <div id="content">
        <h1>Welcome {{user.first_name}}!!!!!</h1>
        <div class="conatiner-account">
        <div class="deatils">
        <h2>Account Details</h2>
        <p id="{{user.id}}">Username: {{user}}</p>
        <p>Name: {{user.first_name}}</p>
        {% if not user.is_registered %}<h3>Your are still not registered!!!<br/> don't miss this chance of beign a part of ACM Nexus!! </h3> {% endif %}
        {% if user.is_registered %} <h3>Congrats!!! You are registered for the event!! </h3>{% endif %}
    </div>
            <div class="buttons">
                <div class="button-container">
                <a onclick="openBlock()">Change Password</a>
        <a href="{% url 'MainApp:logout' %}">Logout</a>
                </div>
            </div>
        </div>
    </div>
{% endblock body %}
{% block script %}
    <script type="text/javascript" src="{% static '/MainApp/account.js' %}"></script>
{% endblock script %}

MainApp/templates/MainApp/confirmation.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
    <link rel="stylesheet" href="{% static 'MainApp/recovery.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0" />
{% endblock head %}
{% block body %}
    <div class="inner-container">
        <span class="material-symbols-outlined">
            check
            </span>
        <div class="text">You will receive mail in your provided mail id in a while.</div>
    </div>
{% endblock body %}

MainApp/templates/MainApp/event.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
    <title> Login and Registration Form </title>
    <link rel="stylesheet" href="{% static 'MainApp/event.css'%}">
    <!-- Fontawesome CDN Link -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    
{% endblock head %}

{% block body %}
<div class="outer-container">
    <div class="inner-container">
        <img src="{% static 'images/cover.jpg' %}" width="100%" alt="">
        <h2 class="title">FRONT-END FIESTADESIGN SHOWDOWN</h2>
        <hr style="width:50%", size="3", color=black>  
        <div class="description">🌟 Embark on a Digital Odyssey: Front-End Fiesta by ACM KLS GIT! 🚀🖥<br>
            Hello, tech enthusiasts! 👋 Get ready for a thrilling 7-day spectacle as ACM KLS GIT introduces Front-End Fiesta – an electrifying event that merges technology and creativity! 🏫<br>
            📢 The Challenge: Transforming Dreams into Digital Realities<br>
            We're on a mission to revolutionize the online presence of 3 government schools. Each school will host 15 dynamic teams, each comprising 3 brilliant minds. Your mission, should you choose to accept it? Craft an extraordinary website for your assigned school! 🌐</br></br>
            🗓 Event Schedule:</br>
            * Start Date: December 26, 2023</br>
            * End Date: January 2, 2024</br></br>
            🌐 Website Development:</br>
            Teams will be assigned to specific schools, and over the first 4 days, create a user-friendly and informative website for your designated school. Showcase your skills and highlight the best features of each institution.</br>
        </br>
            🏆  The Finale Showdown!</br>
            On the final day, all teams will converge for an exhilarating Front-End Fiesta event. Brace yourselves for 3 intense judging rounds where the best of the best will be crowned! 🥇🥈🥉</br>
            Ready to join the digital revolution? 🚀 Don't miss out on this chance to showcase your talents and make a lasting impact on education.</br>
        </br>
            Front-End Fiesta - Register Now!</br>
            Let's redefine the digital landscape together! 🌐✨ #FrontEndFiesta #TechRevolution #ACMKLSGIT</div>
    </div>
</div>
<div class="button">Apply</div>

{% endblock body %}

MainApp/templates/MainApp/home.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
    <title>ACM</title>
    <link rel="stylesheet" href="{% static 'MainApp/home.css'%}">
    
{% endblock head %}
{% block body %}
    <div class="inner-container">
      <div class="event-header ">
      <div class="event-title animate__animated animate__bounceInDown">ACM Nexus</div>
      <div class="event-subtitle animate__animated animate__backInLeft">Unite Through Innovation</div>
    </div>
    <div class="content">
        <div class="overview inner-content">
            <h3>Overview</h3>
            <ul class="points">
                <li><strong>Theme:</strong><br> Innovation across multiple domains</li>
                <li><strong>Objective:</strong><br> Encourage creative solutions to diverse problem statements within the given themes.</li>
                <li><strong>Time:</strong><br> January 5th, 2024, from 1:00 PM to January 6th, 2024, 5:00 PM</li>
                <li><strong>Team size:</strong><br> 4 members per team</li>
            </ul>
        </div>
        <div class="event-timeline inner-content">
            <h3>Event Timeline</h3>
            <ul class="points">
                <li><strong>January 5th, 2024:</strong></li> <ul><li>1:00 PM: Event starts.</li><li>3:00 PM: Round 1 of evaluation</li><li>o	8:00 PM: Round 2 of evaluation</li></ul>
                <li><strong>January 6th, 2024:</strong></li><ul><li>o	11:00 AM: Round 3 of evaluation</li><li>o	1:00 PM: Event ends, project submissions close.</li><li>o	1:30 PM - 3:30 PM: Project presentations and judging.</li><li>o	4:00 PM: Winners announced, closing ceremony.</li></ul>
            </ul>
        </div>
        <div class="General-rules inner-content">
            <h3>General Rules</h3>
            <ul class="points">
                <li><strong>Team Formation:</strong></li> <ul><li>Teams must consist of exactly 4 members</li></ul>
                <li><strong>Eligibility:</strong></li><ul><li>Open to all participants interested in problem-solving and innovation</li><li>Participants must abide by the event's Code of Conduct.</li></ul>
                <li><strong>Project Development:</strong></li> <ul><li>Projects should align with at least one of the provided problem statements</li><li>Use of open-source libraries and APIs is permitted</li></ul>
            </ul>
        </div>
        <div class="submission inner-content">
            <h3>Submission</h3>
            <ul class="points">
                <li>Each team must submit their project by the specified deadline</li>
                <li>Submissions should include a presentation (slides or video) and a brief documentation describing the project.</li>
            </ul>
        </div>
        <div class="judging-ceiteria inner-content">
            <h3>Judging Criteria</h3>
            <ul class="points">
                <li>Projects will be evaluated based on innovation, technical complexity, relevance to the problem statement, and presentation quality.</li>
            </ul>
        </div>
        <div class="code-of-conduct inner-content">
            <h3>Code of Conduct</h3>
            <ul class="points">
                <li>Respectful and ethical behaviour is expected from all participants</li>
                <li>Plagiarism or using someone else's work without attribution is strictly prohibited</li>
            </ul>
        </div>
        <div class="Disclaimer inner-content">
            <h3>Disclaimer</h3>
            <div>ACM KLS GIT reserves the right to modify the event rules and guidelines if deemed necessary. Any changes will be communicated to the participants promptly</div>
        </div>
    </div>
    
    <div class="cover">
end
    </div>
    </div>

{% endblock body %}

MainApp/templates/MainApp/login.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
    <title> Login and Registration Form </title>
    <link rel="stylesheet" href="{% static 'MainApp/login.css'%}">
    <!-- Fontawesome CDN Link -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">

{% endblock head %}

{% block body %}
  <div class="conatiner-inner">
    <input type="checkbox" id="flip">
    <div class="cover">
      <div class="front">
        <img src="{% static 'Images/frontImg.jpg' %}" alt="">
        <div class="text">
          <span class="text-1">ACM Nexus</span>
          <span class="text-2">Unite Through Innovation</span>
        </div>
      </div>
      <div class="back">
        <img class="backImg" src="{% static 'Images/backImg.jpg' %}" alt="">
        <div class="text">
          <span class="text-1">ACM Nexus</span>
          <span class="text-2">Unite Through Innovation</span>
        </div>
      </div>
    </div>
    <div class="forms">
        <div class="form-content">
          <div class="login-form">
            <div class="title">Login</div>
            {% csrf_token %}
            <div class="input-boxes">
              <div class="input-box">
                <i class="fas fa-envelope"></i>
                <input type="text" placeholder="Enter your email" id="email" required>
              </div>
              <div class="input-box">
                <i class="fas fa-lock"></i>
                <input type="password" id='password' placeholder="Enter your password" required>
              </div>
              <div class="text"><a href="{% url 'MainApp:recovery' %}">Forgot password?</a></div>
              <div class="button input-box">
                <input type="submit" value="Submit" onclick="login()">
              </div>
              <div class="text sign-up-text">Don't have an account? <label for="flip">Sigup now</label></div>
            </div>
      </div>
        <div class="signup-form">
          <div class="title">Signup</div>
        <form action="{% url 'MainApp:register' %}" onsubmit="return validateForm()" method="post">
          {% csrf_token %}
            <div class="input-boxes">
              <div class="input-box">
                <i class="fas fa-user"></i>
                <input type="text" id="name" name="name" placeholder="Enter your name" required>
              </div>
              <div class="input-box">
                <i class="fas fa-user"></i>
                <input type="text" id="USN" name="USN" placeholder="Enter your USN" required>
              </div>
              <div class="input-box">
                <i class="fas fa-user"></i>
                <input type="number" id="year" name="year" placeholder="Year of Graduation:" required>
              </div>
              <div class="input-box">
                <i class="fas fa-envelope"></i>
                <input type="text" id='' name="email" placeholder="Enter your email" required>
              </div>

              <div class="button input-box">
                <input type="submit" value="Submit">
              </div>
              <div class="text sign-up-text">Already have an account? <label for="flip">Login now</label></div>
            </div>
      </form>
    </div>
    </div>
    </div>
  </div>
{% endblock body %}
{% block script %}
<script type="text/javascript" src="{% static '/MainApp/login.js' %}"></script>
{% endblock script %}

MainApp/templates/MainApp/problems.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
    <title>About</title>
    <link rel="stylesheet" href="{% static 'MainApp/problems.css'%}">
    
{% endblock head %}

{% block body %}
    <div class="inner-container">
        <div class="about-header">
            <span class="title-about">Problems</span>
        </div>
        <main class="main">
          {% for themes,val in theme %}
            <section class="section">
              <h2 class="heading">{{val}}</h2>
              {% for problems in data %}
                 {% if problems.0 == themes %} 
                    {% for problem in problems.1 %}
                        <div class="card">
                            <div class="card-header">
                                <h3 class="card-header-title">Problem No: {{problem.0}}</h3>
                            </div>
                            <div class="card-content">
                                <p>{{problem.1}}</p>
                            </div>
                        </div>
                    {% endfor %}
                 {%endif%}
              {% endfor %}
            </section>
        {% endfor %}
          </main>

</div>


{% endblock body %}
{% block script %}
    <!-- <script type="text/javascript" src="{% static '/MainApp/account.js' %}"></script> -->
{% endblock script %}

MainApp/templates/MainApp/recovery.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
    <link rel="stylesheet" href="{% static 'MainApp/recovery.css' %}">
{% endblock head %}
{% block body %}
    <form class="inner-container" method="post" action="{% url 'MainApp:sendpassword' %}">
        {% csrf_token %}
        <label for="email" class="label-email">Enter registered mail id </label><input id="email" name="email" type="email" placeholder="Email id" required>
        <input type="submit" class="submit">
    </form>
{% endblock body %}

MainApp/templates/MainApp/registered.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
    <link rel="stylesheet" href="{% static 'MainApp/registered.css' %}">
{% endblock head %}
{% block body %}
<form action="../deleteteam/{{team.team_name}}" method="post" class="block" id="block" onsubmit="return validateForm()">
    <div class="inner-block">
        {% csrf_token %}
        <h1>Do u really want to delete the team?</h1>
        <div class="button">
            <div class="cancel" onclick="closeBlock()">Cancel</div>
            <input class="submit" type="submit" value="Delete">
        </div>
    </div>
</form>
    <div id="content">
        <h1>Welcome {{team.team_name}}!!!!!</h1>
        <div class="conatiner-account">
        <div class="deatils">
        <h2>Team Details</h2>
        <p id="{{team.id}}">Team Name: {{team.team_name}}</p>
        <p>Problem Number: {{team.problem_no}}</p>
        <p>Team Leader: {{team.team_leader}}</p>
            <p>Member 1: {{team.team_member1}}</p>
            <p>Member 2: {{team.team_member2}}</p>
            <p>Member 3: {{team.team_member3}}</p>
            <h2><a href="https://chat.whatsapp.com/KYDljOQMUI0GoWQqZ7Fiou">Click here</a> to join the whatsapp group!!</h2>
    </div>
            {% if user.email == team.team_leader.email %}<div class="buttons">
                <div class="button-container">
                <a onclick="openBlock()">Delete Team</a>
                </div>
            </div>
            {% endif %}
        </div>
    </div>
{% endblock body %}
{% block script %}
    <script type="text/javascript" src="{% static '/MainApp/registered.js' %}"></script>
{% endblock script %}

MainApp/templates/MainApp/registration.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
    <link rel="stylesheet" href="{% static 'MainApp/registration.css' %}">
{% endblock head %}
{% block body %}
        
        <form method="post" action="#" id="form" class="inner-container" onsubmit="return validateForm()">
            {% csrf_token %}
            <div class="title">Registration</div>
            <div class="input-boxes">
                <div class="input-box">
                    <i class="fas fa-user"></i>
                    <input type="text" id="name" name="name" placeholder="Team Name"  required >
                </div>
                <div class="input-box">
                    <i class="fas fa-lock"></i>
                    <input type="number" id='problem' name="problem" placeholder="Problem Number" required>
                </div>
                <div class="input-box">
                    <i class="fas fa-user"></i>
                    <input type="email" id="email1" name="email1" placeholder="Email member 1" value="{{ user.email }}" readonly required>
                </div>
                <div class="input-box">
                    <i class="fas fa-envelope"></i>
                    <input type="email" id="email2" name="email2" placeholder="Email member 2" required>
                </div>
                <div class="input-box">
                    <i class="fas fa-lock"></i>
                    <input type="email" id='email3' name="email3" placeholder="Email member 3" required>
                </div>
                <div class="input-box">
                    <i class="fas fa-lock"></i>
                    <input type="email" id='email4' name="email4" placeholder="Email member 4" required>
                </div>
                <div class="button input-box">
                    <input type="submit" value="Submit">
                </div>
            </div>
        </form>

{% endblock body %}
{% block script %}
<script type="text/javascript" src="{% static '/MainApp/registration.js' %}"></script>
{% endblock script %}